Update .NETBuild.yml

diff --git a/.github/workflows/.NETBuild.yml b/.github/workflows/.NETBuild.yml
--- a/.github/workflows/.NETBuild.yml
+++ b/.github/workflows/.NETBuild.yml
@@ -14,6 +14,8 @@ on:
 jobs:
   build-and-test:
     runs-on: ubuntu-latest
+    timeout-minutes: 15  # Increase timeout duration
+    
     steps:
     - name: Checkout
       uses: actions/checkout@v3
@@ -27,8 +29,8 @@ jobs:
     - name: Build the project
       run: dotnet build BucStop
 
-    # Start BucStop application using systemd
-    - name: Start BucStop
+    # Write BucStop service file to the repository directory
+    - name: Write BucStop service file
       run: |
         echo "[Unit]
         Description=BucStop
@@ -43,10 +45,23 @@ jobs:
         User=$USER
 
         [Install]
-        WantedBy=multi-user.target" > /etc/systemd/system/bucstop.service
+        WantedBy=multi-user.target" > $GITHUB_WORKSPACE/bucstop.service
+
+    # Start BucStop application using systemd
+    - name: Start BucStop
+      run: |
+        sudo cp $GITHUB_WORKSPACE/bucstop.service /etc/systemd/system/bucstop.service
         sudo systemctl daemon-reload
         sudo systemctl start bucstop.service
+
+    # Wait for BucStop to be ready
+    - name: Wait for BucStop to start
+      run: |
+        echo "Waiting for BucStop to start..."
+        sleep 20  # Adjust sleep time as needed
+        curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 60 --retry-all-errors http://localhost:7182/ || true  # Use || true to prevent workflow failure if curl fails
 
     # Run regression tests
     - name: Run Regression Tests
       run: dotnet test BucStop/BucStop.csproj
+
